U-Coach.Server/MvcAuthrorization/Models/LogonModel.cs
namespace MvcAuthrorization.Models
{
    public class LogonModel
    {
        public string Login { get; set; }
        public string Password { get; set; }
    }
}

U-Coach.Server/MvcAuthrorization/Models/UserProfileModel.cs
namespace MvcAuthrorization.Models
{
    public class UserProfileModel
    {
        public string Id { get; set; }
    }
}

U-Coach.Server/MvcAuthrorization/Controllers/AuthenticationController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using MvcAuthrorization.Models;
using PVDevelop.UCoach.Server.WebApi;
using PVDevelop.UCoach.Server.Role.Contract;
using PVDevelop.UCoach.Server.HttpGateway.Contract;

namespace MvcAuthrorization.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IActionResultBuilderFactory _actionResultBuilderFactory;

        public AuthenticationController(IActionResultBuilderFactory actionResultBuilderFactory)
        {
            if (actionResultBuilderFactory == null)
            {
                throw new ArgumentNullException(nameof(actionResultBuilderFactory));
            }
            _actionResultBuilderFactory = actionResultBuilderFactory;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(new LogonModel());
        }

        [HttpPost]
        public async Task<ActionResult> LogonFacebook(LogonModel model)
        {
            using (var builder = _actionResultBuilderFactory.CreateActionResultBuilder())
            {
                var response =
                    await builder.
                    AddParameter("redirect_uri", GetFacebookCodeRedirectUri()).
                    BuildGetAsync(PVDevelop.UCoach.Server.HttpGateway.Contract.Routes.FACEBOOK_REDIRECT_URI);

                var result =
                    response.
                    EnsureSuccessStatusCode().
                    ToJson<FacebookRedirectDto>();

                return Redirect(result.Uri);
            }
        }

        [HttpGet]
        public async Task<ActionResult> FacebookCode(string code)
        {
            using (var builder = _actionResultBuilderFactory.CreateActionResultBuilder())
            {
                var logonDto = new FacebookLogonDto()
                {
                    Code = code,
                    RedirectUri = GetFacebookCodeRedirectUri()
                };

                var response =
                    await builder.
                    BuildPutAsync(PVDevelop.UCoach.Server.HttpGateway.Contract.Routes.FACEBOOK_LOGON, logonDto);

                var result =
                    response.
                    EnsureSuccessStatusCode();

                result.CopyCookies(Response);

                return RedirectToHome();
            }
        }

        [HttpPost]
        public async Task<ActionResult> LogonUCoach(LogonModel model)
        {
            using (var builder = _actionResultBuilderFactory.CreateActionResultBuilder())
            {
                var logonDto = new UCoachLogonDto()
                {
                    Login = model.Login,
                    Password = model.Password
                };

                var response =
                    await builder.
                    BuildPutAsync(PVDevelop.UCoach.Server.HttpGateway.Contract.Routes.UCOACH_LOGON, logonDto);

                var result =
                    response.
                    EnsureSuccessStatusCode();

                result.CopyCookies(Response);

                return RedirectToHome();
            }
        }

        private ActionResult RedirectToHome()
        {
            return RedirectToAction("Index", "Home");
        }

        private string GetFacebookCodeRedirectUri()
        {
            return string.Format(
                "{0}://{1}/Authentication/FacebookCode",
                Request.Url.Scheme,
                Request.Url.Authority);
        }
    }
}

U-Coach.Server/MvcAuthrorization/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcAuthrorization.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

U-Coach.Server/MvcAuthrorization/Controllers/UserProfileController.cs
using System;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;
using MvcAuthrorization.Models;
using PVDevelop.UCoach.Server.Role.Contract;
using PVDevelop.UCoach.Server.WebApi;

namespace MvcAuthrorization.Controllers
{
    public class UserProfileController : Controller
    {
        private readonly IActionResultBuilderFactory _actionResultBuilderFactory;

        public UserProfileController(IActionResultBuilderFactory actionResultBuilderFactory)
        {
            if (actionResultBuilderFactory == null)
            {
                throw new ArgumentNullException(nameof(actionResultBuilderFactory));
            }
            _actionResultBuilderFactory = actionResultBuilderFactory;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            try
            {
                using (var builder = _actionResultBuilderFactory.CreateActionResultBuilder())
                {
                    var userIdDto = (await
                        builder.
                        AddCookies(Request.ToCookieCollection()).
                        BuildGetAsync(PVDevelop.UCoach.Server.HttpGateway.Contract.Routes.USER_INFO)).
                        EnsureSuccessStatusCode().
                        ToJson<UserIdDto>();

                    var profileModel = new UserProfileModel()
                    {
                        Id = userIdDto.Id.ToString()
                    };

                    return View(profileModel);
                }
            }
            catch
            {
                return RedirectToAction("Index", "Authentication");
            }
        }

        [HttpPost]
        public async Task<ActionResult> Logout()
        {
            using (var builder = _actionResultBuilderFactory.CreateActionResultBuilder())
            {
                var result = (await 
                    builder.
                    AddCookies(Request.ToCookieCollection()).
                    BuildDeleteAsync(PVDevelop.UCoach.Server.HttpGateway.Contract.Routes.LOGOUT)).
                    EnsureSuccessStatusCode();

                result.CopyCookies(Response);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

U-Coach.Server/MvcAuthrorization/Views/Authentication/Index.cshtml
@model MvcAuthrorization.Models.LogonModel
@{
    ViewBag.Title = "Authentication";
}

<h2>Authentication</h2>

@using (Html.BeginForm("LogonUCoach", "Authentication", FormMethod.Post))
{
    @Html.LabelFor(m => m.Login)
    @Html.EditorFor(m => m.Login)

    @Html.LabelFor(m => m.Password)
    @Html.EditorFor(m => m.Password)

    <input type="submit" value="Logon"/>
}

@using (Html.BeginForm("LogonFacebook", "Authentication", FormMethod.Post))
{
    <input type="submit" value="Facebook"/>
}

U-Coach.Server/MvcAuthrorization/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@Html.ActionLink("Logon", "Index", "Authentication")
@Html.ActionLink("Resource", "Index", "UserProfile")

U-Coach.Server/MvcAuthrorization/Views/Resource/Index.cshtml
@{
    ViewBag.Title = "Resource";
}

<h2>Authorized resource</h2>

U-Coach.Server/MvcAuthrorization/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UCoach</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

U-Coach.Server/MvcAuthrorization/Views/UserProfile/Index.cshtml
@model MvcAuthrorization.Models.UserProfileModel
@{
    ViewBag.Title = "UserProfile";
}

<h2>UserProfile</h2>

@Html.LabelFor(p=>p.Id)
@Html.DisplayTextFor(p=>p.Id)

@using (Html.BeginForm("Logout", "UserProfile", FormMethod.Post))
{
    <input type="submit" value="Logout" />
}